### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by DaanMoura** [DaanMoura/Compiladores-Lua#2]
O que devemos fazer:

- [x] Análise Léxica
  - [x] Constantes Numéricas
  - [x] Cadeias de caracteres
  - [x] Operadores
  - [x] Whitespace e comentários
- [x] Análise Sintática
  - [x] Trecho
  - [x] Bloco
  - [x] Comando e Último Comando
  - [x] Nome da Função
  - [x] Variável
  - [x] Lista de Nomes
  - [x] Expressões, lista de expressões e prefixo de expressões
  - [x] Chamada de Funções
  - [x] Argumentos
  - [x] Função e Corpo da Função
  - [x] listapar
  - [x] Construtor de Tabela
  - [x] Campos, lista de Campos e separador de campos
